AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Ec2 instance"

Parameters:
  InstanceTypeParamter: 
    Description: Select instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.large
    Description: Enter t2.micro, t2.small, or t2.large. Default is t2.micro.


Resources:
  Instance: # logical id
    Type: AWS::EC2::Instance # type 
    Properties:
      InstanceType: !Ref InstanceTypeParamter
      ImageId: ami-052cef05d01020f1d
      Tags:
        - Key: Name
          Value: cf-demo

  NewVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 50
      AvailabilityZone:
        !GetAtt Instance.AvailabilityZone

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId:
        !Ref Instance
      VolumeId:
        !Ref NewVolume
      Device: /dev/sdh

Outputs:
    InstanceName:
      Value: !Ref Instance
    DNSName:    
      Value: !GetAtt Instance.PublicDnsName    
