AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates S3 bucket | Join"

Parameters:
  S3BucketName:
    Description: Enter S3 bucket name
    Type: String
    MinLength: 3
    MaxLength: 10
    AllowedPattern: "[A-Za-z]+"

Resources:
  S3Bucket: # logical id/name
    Type:  AWS::S3::Bucket # Type of resource
    Properties:
      BucketName: !Join ['-', [ !Ref S3BucketName, !Ref AWS::Region, !Ref AWS::StackName ]]
        